### ISSUE TITLE
DMB barrier for H2D transfers

### ISSUE THREAD

**Issue by daniestevez** [FutureSDR/xilinx-dma#2]
Hi,

My understanding about how the ARM memory model works (but I'm far from an expert on this topic) regarding host to device DMA transfers is the following. The AXI4-Lite control interface of the AXI-DMA is device memory, so writes to its registers are not reordered by hardware. However, the buffer we write in DDR sits in normal memory. Writes to normal memory can be reordered among themselves and also with respect to writes to device memory, if I remember correctly. This means that when we write data to the buffer to perform an H2D transfer and then we write to the AXI-DMA registers to set up and start this transfer, there is no guarantee that the writes to DDR have been observed by the hardware by the time that the writes to the AXI-DMA registers are observed. In theory, this means that the AXI-DMA could potentially start reading data from DDR that hasn't been written yet.

In other applications I've done that controlled the AXI-DMA from userspace, I used a `dmb` instruction before writing to the registers of the AXI-DMA to configure an H2D transfer, in order to ensure that all the writes to the DDR buffer have been observed before proceeding with the set up of the AXI-DMA. I don't know if there is an easy to way to do this with stable Rust. I googled a bit and all the solutions I saw required nightly.

In practice this is not very important, because not including the barrier is unlikely to give problems. Typically the ARM is much faster in writing to DDR than the AXI-DMA is reading it, so it won't happen that the AXI-DMA will manage to fetch the data before the writes done by the ARM have been observed by the DDR, specially when the buffers that are transferred are not very small.

This crate is certainly working well for me without a barrier, but it might be good to keep these ideas for the future.

By the way I don't know what is the technically correct solution for D2H transfers regarding barriers. I've never done anything special in my applications in this case.

**Comment by bastibl** [comment]
Here be dragons :-) Tbh, I don't have a good idea. I think the volatile writes make sure that the compiler doesn't reorder. And, as you mentioned, the configuration of the AXI4-lite device memory makes sure that the writes are not reordered by the CPU. (I didn't find a reference for this, but all examples do sequential volatile writes to DMA registers without barriers. So, I'd take this for granted.) When implementing it, I thought that the fact that I disable CPU caches for the DMA buffer would be enough. But you're right, it looks like there is no guarantee that writes to the DMA buffer are not reordered with the writes to the registers :-( It might even need a compile fence to make sure that the function, issuing the transfer is not inlined and reordered. The crate for the Cortex M does it like this: https://github.com/rust-embedded/cortex-m/blob/master/asm/inline.rs#L69-L74
The `__dmb` instruction already comes with a compiler fence: https://doc.rust-lang.org/core/arch/arm/fn.__dmb.html

Given the fact that the project is experimental, I think it would be fine to require nightly. Alternatively, one could wrap a C function that does it.  Would you give either approach a try? I don't have the HW available at the moment, so I could only compile test.

For the other direction (D2H), I think it should be fine. When the interrupt is raised, the transfer should be complete, and since there is no caching, we should see the correct data.

I plan to dig deeper into this topic in the next months and compare the performance of different coherency modes and FPGA interfaces (e.g., HPC ports of MPSoCs). At the moment I only have an MPSoC board. Is your 7000 series board something you would recommend?

**Comment by daniestevez** [comment]
I don't have a good idea either :-)

I think the good reference to try to understand these things is the [ARM architecture reference manual](https://developer.arm.com/documentation/ddi0406/latest). (Take note that I'm linking the manual for ARMv7; the MPSoC is ARMv8, and I think it has more memory types). In Section A3.8 it explains all this stuff. In particular, there is this table summarizing the ordering of accesses.

![accesses](https://user-images.githubusercontent.com/15093841/133133807-097ff518-23e0-4474-84e3-64c3b26a94c3.png)

My understanding from that table is that accesses to the same device are never reordered. However, accesses to the normal memory can be reordered with respect to accesses to the device.

> It might even need a compile fence to make sure that the function, issuing the transfer is not inlined and reordered.

I'm not sure if that could happen. As you point out, the volatile accesses prevent the compiler from reordering access to non-volatile memory with respect to accesses to volatile memory. I would assume that the same would happen if the function is inlined. The good thing about these reorderings done by the compiler is that we can read the binary to see what the compiler did (though not a complete guarantee about what it *may* do!). Understanding or seeing the reorderings done by hardware is more difficult.

> The __dmb instruction already comes with a compiler fence

I think it's pretty pointless to insert a `dmb` if the compiler can reorder it with respect to some memory access (volatile or not) so I would take that for granted in any correct way to insert `dmb`.

I'll perhaps give a try to wrapping the `dmb` in a C function. I don't know the details about calling C from Rust, but when calling C from C the compiler can't reorder memory accesses with respect to a function call (and I would assume the same is true for Rust extern functions).

> For the other direction (D2H), I think it should be fine. When the interrupt is raised, the transfer should be complete, and since there is no caching, we should see the correct data.

Maybe I'm always double-thinking these things, but in this case I'm not completely sure if at the moment when the AXIDMA gets a write response from the HP0 port (or to whatever AXI slave it is connected) then the transfer is still on its way to the DDR controller or has actually been committed by the DDR controller.

The Zynq-7000 board that I have is a Zedboard, and I just have it just because some other project. In my opinion these days it's perhaps a bit pricey compared to other boards. On the other hand it is a really popular and user-friendly board, so that pays off in terms of tutorials, example projects, etc. I think that the MPSoC is slowly superseding all the Zynq-7000's, except perhaps for some low cost or low power applications. In general the MPSoC is a more capable platform (and look at the cost of the Kria SOM dev board!). So perhaps it doesn't make sense for you to get a Zynq-7000 if you have an MPSoC, unless you want to compare the performance between them.

Another Zynq-7000 platform that people overlook is the Pluto. I bet most of us have one of them lying around. The FPGA is small, and it's a bit awkward as a development platform because of the lack of serial and JTAG (but you can solder those). For testing a simple accelerator and two AXIDMAs as you used in your example, I think it's adequate.

**Comment by daniestevez** [comment]
I just gave a try to wrapping `dmb` in a C function in #3. Still haven't tested this on hardware. I'll let you know how it goes.

**Comment by bastibl** [comment]
Thanks for your reply. Really great to have this conversation!

I think regarding the compiler fence, there was a misunderstanding. Volatile writes are not reordered. But if stuff gets inlined, one might end up with writes to the DMA buffer followed by volatile writes to the DMA registers. In this situation, there seems to be no guarantee that Rust doesn't reorder the writes to the DMA buffer after the volatile writes to the DMA registers. I think this is the reason why both the Rust std lib and the Cortex crate stress the compiler fence. I don't know how smart the compiler is and with an external function it might not be an issue, but the compiler fence is just a compile-time thing that doesn't cause runtime overhead and just prevents potential optimizations that shouldn't happen in the first place. So, adding them shouldn't hurt :-)

Regarding the D2H transfer. I couldn't find a clear statement that what you mention cannot happen. But I wouldn't know how to use the DMA controller, if this is not guaranteed. Or if it, at least, guarantees that the write to the DDR is enqueued in the controller and will be visible before any subsequent read from issued from the CPU. I wouldn't know of any other mechanism to make sure that the transfer is guaranteed to be visible :-/ I looked at a bare metal example from Xilinx. At least there, they only seem to wait for the IRQ without any subsequent checks or tricks. https://www.xilinx.com/support/answers/57562.html

Thanks for the PR and the comments about the boards. I'd be interested to compare also with a Zynq. If I can reimburse it from university, I'll try to get a ZedBoard.

**Comment by daniestevez** [comment]
I see what you mean regarding inlining. I was mistakenly thinking that the compiler cannot reorder non-volatile writes with respect to volatile writes. I've just seen that this is not true in C. Agreed that adding a `compiler_fence(Ordering::SeqCst);` as in the cortex-m crate is a good idea. This is available in stable Rust, so no reason not to put it in.

I think that if calling `dmb` in an external function as I'm doing in #3, then the compiler cannot reorder memory accesses across the external function call, since that function may touch memory freely. Still I would put the `compiler_fence` just in case the function call is eventually replaced with inline asm.

By the way I tested the code in #3 today on the Zedboard, and it seems to run just fine.

You make a very good point regarding the D2H transfer. If there is no guarantee from hardware that the transfer has "really finished", it would be impossible to know with certainty how much to wait.

**Comment by bastibl** [comment]
Not the best idea to add the "fixes" to the commit that increments the version :-) Anyways, thanks for bringing this up and for working on the issue.
